# Generated by Django 4.1.4 on 2022-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmName', models.CharField(max_length=50)),
                ('date_out', models.IntegerField(max_length=8)),
                ('date_view', models.IntegerField(max_length=8)),
                ('actors', models.TextField()),
            ],
        ),
    ]
