# Generated by Django 4.1.4 on 2022-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gyskov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_out',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_view',
            field=models.IntegerField(),
        ),
    ]
