# Generated by Django 4.1.4 on 2022-12-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gyskov', '0002_alter_film_date_out_alter_film_date_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='FilmID',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='date_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_view',
            field=models.DateField(),
        ),
    ]
