# Generated by Django 4.1.4 on 2022-12-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gyskov', '0003_film_filmid_alter_film_date_out_alter_film_date_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='FilmID',
        ),
    ]
