# Generated by Django 4.1.4 on 2022-12-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gyskov', '0004_remove_film_filmid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='FilmCategory',
            new_name='category',
        ),
    ]
