# Generated by Django 4.1.4 on 2022-12-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gyskov', '0005_rename_filmcategory_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='FilmName',
            new_name='name',
        ),
    ]
