# Generated by Django 4.1.4 on 2022-12-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gyskov', '0006_rename_filmname_film_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
