# Generated by Django 4.1.4 on 2022-12-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gyskov', '0007_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Films',
        ),
    ]
